### ISSUE TITLE
cannot setup pycaret on pccompute

### ISSUE THREAD

**Issue by suredream** [microsoft/PlanetaryComputer#125]
```
!pip install pycaret
```

got the following error message, any idea?

```
error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [388 lines of output]
      Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX" and platform_python_implementation == "CPython"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX" and platform_python_implementation != "CPython"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
      Collecting setuptools
        Using cached setuptools-65.5.0-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting Cython>=0.28.5
        Using cached Cython-0.29.32-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (2.0 MB)
      Collecting numpy==1.17.3
        Using cached numpy-1.17.3.zip (6.4 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting scipy>=0.19.1
        Using cached scipy-1.9.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.8 MB)
        Using cached scipy-1.9.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.8 MB)
        Using cached scipy-1.9.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.9 MB)
        Using cached scipy-1.9.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.9 MB)
        Using cached scipy-1.8.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (42.2 MB)
      Building wheels for collected packages: numpy
        Building wheel for numpy (setup.py): started
        Building wheel for numpy (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [152 lines of output]
            Running from numpy source directory.
            blas_opt_info:
            blas_mkl_info:
            customize UnixCCompiler
            C compiler: /srv/conda/envs/notebook/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /srv/conda/envs/notebook/include -fPIC -O2 -isystem /srv/conda/envs/notebook/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /srv/conda/envs/notebook/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /srv/conda/envs/notebook/include -fPIC
      
            creating /tmp/tmpc104cakj/tmp
            creating /tmp/tmpc104cakj/tmp/tmpc104cakj
            compile options: '-MMD -MF /tmp/tmpc104cakj/file.c.d -c'
            x86_64-conda-linux-gnu-cc: /tmp/tmpc104cakj/file.c
              FOUND:
                libraries = ['mkl_rt', 'pthread']
                library_dirs = ['/srv/conda/envs/notebook/lib']
                define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
                include_dirs = ['/usr/local/include', '/usr/include', '/srv/conda/envs/notebook/include']
      
              FOUND:
                libraries = ['mkl_rt', 'pthread']
                library_dirs = ['/srv/conda/envs/notebook/lib']
                define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
                include_dirs = ['/usr/local/include', '/usr/include', '/srv/conda/envs/notebook/include']
      
            /bin/sh: 1: svnversion: not found
            non-existing path in 'numpy/distutils': 'site.cfg'
            lapack_opt_info:
            lapack_mkl_info:
            customize UnixCCompiler
            C compiler: /srv/conda/envs/notebook/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /srv/conda/envs/notebook/include -fPIC -O2 -isystem /srv/conda/envs/notebook/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /srv/conda/envs/notebook/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /srv/conda/envs/notebook/include -fPIC
      
            creating /tmp/tmp3xjwteue/tmp
            creating /tmp/tmp3xjwteue/tmp/tmp3xjwteue
            compile options: '-MMD -MF /tmp/tmp3xjwteue/file.c.d -c'
            x86_64-conda-linux-gnu-cc: /tmp/tmp3xjwteue/file.c
              FOUND:
                libraries = ['mkl_rt', 'pthread']
                library_dirs = ['/srv/conda/envs/notebook/lib']
                define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
                include_dirs = ['/usr/local/include', '/usr/include', '/srv/conda/envs/notebook/include']
      
              FOUND:
                libraries = ['mkl_rt', 'pthread']
                library_dirs = ['/srv/conda/envs/notebook/lib']
                define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
                include_dirs = ['/usr/local/include', '/usr/include', '/srv/conda/envs/notebook/include']
      
            /srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/dist.py:262: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            running bdist_wheel
            running build
            running config_cc
            unifing config_cc, config, build_clib, build_ext, build commands --compiler options
            running config_fc
            unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
            running build_src
            build_src
            building py_modules sources
            creating build
            creating build/src.linux-x86_64-3.9
            creating build/src.linux-x86_64-3.9/numpy
            creating build/src.linux-x86_64-3.9/numpy/distutils
            building library "npymath" sources
            get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
            customize Gnu95FCompiler
            Could not locate executable gfortran
            Could not locate executable f95
            customize IntelFCompiler
            Could not locate executable ifort
            Could not locate executable ifc
            customize LaheyFCompiler
            Could not locate executable lf95
            customize PGroupFCompiler
            Could not locate executable pgfortran
            customize AbsoftFCompiler
            Could not locate executable f90
            Could not locate executable f77
            customize NAGFCompiler
            customize VastFCompiler
            customize CompaqFCompiler
            Could not locate executable fort
            customize IntelItaniumFCompiler
            Could not locate executable efort
            Could not locate executable efc
            customize IntelEM64TFCompiler
            customize GnuFCompiler
            Could not locate executable g77
            customize G95FCompiler
            Could not locate executable g95
            customize PathScaleFCompiler
            Could not locate executable pathf95
            customize NAGFORCompiler
            Could not locate executable nagfor
            don't know how to compile Fortran code on platform 'posix'
            C compiler: /srv/conda/envs/notebook/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /srv/conda/envs/notebook/include -fPIC -O2 -isystem /srv/conda/envs/notebook/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /srv/conda/envs/notebook/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /srv/conda/envs/notebook/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/srv/conda/envs/notebook/include/python3.9 -c'
            x86_64-conda-linux-gnu-cc: _configtest.c
            /srv/conda/envs/notebook/bin/x86_64-conda-linux-gnu-cc _configtest.o -o _configtest
            /srv/conda/envs/notebook/bin/../lib/gcc/x86_64-conda-linux-gnu/12.1.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lgcc
            /srv/conda/envs/notebook/bin/../lib/gcc/x86_64-conda-linux-gnu/12.1.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lgcc
            collect2: error: ld returned 1 exit status
            failure.
            removing: _configtest.c _configtest.o _configtest.o.d
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/setup.py", line 443, in <module>
                setup_package()
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/setup.py", line 435, in setup_package
                setup(**metadata)
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/numpy/distutils/core.py", line 171, in setup
                return old_setup(**new_attr)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
                return distutils.core.setup(**attrs)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
                return run_commands(dist)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                dist.run_commands()
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
                self.run_command(cmd)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
                super().run_command(command)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                cmd_obj.run()
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
                self.run_command('build')
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
                self.distribution.run_command(command)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
                super().run_command(command)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                cmd_obj.run()
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/numpy/distutils/command/build.py", line 47, in run
                old_build.run(self)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
                self.run_command(cmd_name)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
                self.distribution.run_command(command)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
                super().run_command(command)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                cmd_obj.run()
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/numpy/distutils/command/build_src.py", line 142, in run
                self.build_sources()
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/numpy/distutils/command/build_src.py", line 153, in build_sources
                self.build_library_sources(*libname_info)
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/numpy/distutils/command/build_src.py", line 286, in build_library_sources
                sources = self.generate_sources(sources, (lib_name, build_info))
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/numpy/distutils/command/build_src.py", line 369, in generate_sources
                source = func(extension, build_dir)
              File "numpy/core/setup.py", line 669, in get_mathlib_info
                raise RuntimeError("Broken toolchain: cannot link a simple C program")
            RuntimeError: Broken toolchain: cannot link a simple C program
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
        Running setup.py clean for numpy
        error: subprocess-exited-with-error
      
        × python setup.py clean did not run successfully.
        │ exit code: 1
        ╰─> [10 lines of output]
            Running from numpy source directory.
      
            `setup.py clean` is not supported, use one of the following instead:
      
              - `git clean -xdf` (cleans all files)
              - `git clean -Xdf` (cleans all versioned files, doesn't touch
                                  files that aren't checked into the git repo)
      
            Add `--force` to your command to use it anyway if you must (unsupported).
      
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for numpy
      Failed to build numpy
      Installing collected packages: wheel, setuptools, numpy, Cython, scipy
        Running setup.py install for numpy: started
        Running setup.py install for numpy: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Running setup.py install for numpy did not run successfully.
        │ exit code: 1
        ╰─> [163 lines of output]
            Running from numpy source directory.
      
            Note: if you need reliable uninstall behavior, then install
            with pip instead of using `setup.py install`:
      
              - `pip install .`       (from a git repo or downloaded source
                                       release)
              - `pip install numpy`   (last NumPy release on PyPi)
      
      
            blas_opt_info:
            blas_mkl_info:
            customize UnixCCompiler
            C compiler: /srv/conda/envs/notebook/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /srv/conda/envs/notebook/include -fPIC -O2 -isystem /srv/conda/envs/notebook/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /srv/conda/envs/notebook/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /srv/conda/envs/notebook/include -fPIC
      
            creating /tmp/tmphqamwzwz/tmp
            creating /tmp/tmphqamwzwz/tmp/tmphqamwzwz
            compile options: '-MMD -MF /tmp/tmphqamwzwz/file.c.d -c'
            x86_64-conda-linux-gnu-cc: /tmp/tmphqamwzwz/file.c
              FOUND:
                libraries = ['mkl_rt', 'pthread']
                library_dirs = ['/srv/conda/envs/notebook/lib']
                define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
                include_dirs = ['/usr/local/include', '/usr/include', '/srv/conda/envs/notebook/include']
      
              FOUND:
                libraries = ['mkl_rt', 'pthread']
                library_dirs = ['/srv/conda/envs/notebook/lib']
                define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
                include_dirs = ['/usr/local/include', '/usr/include', '/srv/conda/envs/notebook/include']
      
            /bin/sh: 1: svnversion: not found
            non-existing path in 'numpy/distutils': 'site.cfg'
            lapack_opt_info:
            lapack_mkl_info:
            customize UnixCCompiler
            C compiler: /srv/conda/envs/notebook/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /srv/conda/envs/notebook/include -fPIC -O2 -isystem /srv/conda/envs/notebook/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /srv/conda/envs/notebook/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /srv/conda/envs/notebook/include -fPIC
      
            creating /tmp/tmp6ju63116/tmp
            creating /tmp/tmp6ju63116/tmp/tmp6ju63116
            compile options: '-MMD -MF /tmp/tmp6ju63116/file.c.d -c'
            x86_64-conda-linux-gnu-cc: /tmp/tmp6ju63116/file.c
              FOUND:
                libraries = ['mkl_rt', 'pthread']
                library_dirs = ['/srv/conda/envs/notebook/lib']
                define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
                include_dirs = ['/usr/local/include', '/usr/include', '/srv/conda/envs/notebook/include']
      
              FOUND:
                libraries = ['mkl_rt', 'pthread']
                library_dirs = ['/srv/conda/envs/notebook/lib']
                define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
                include_dirs = ['/usr/local/include', '/usr/include', '/srv/conda/envs/notebook/include']
      
            /srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/dist.py:262: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            running install
            /srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
              warnings.warn(
            running build
            running config_cc
            unifing config_cc, config, build_clib, build_ext, build commands --compiler options
            running config_fc
            unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
            running build_src
            build_src
            building py_modules sources
            building library "npymath" sources
            get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
            customize Gnu95FCompiler
            Could not locate executable gfortran
            Could not locate executable f95
            customize IntelFCompiler
            Could not locate executable ifort
            Could not locate executable ifc
            customize LaheyFCompiler
            Could not locate executable lf95
            customize PGroupFCompiler
            Could not locate executable pgfortran
            customize AbsoftFCompiler
            Could not locate executable f90
            Could not locate executable f77
            customize NAGFCompiler
            customize VastFCompiler
            customize CompaqFCompiler
            Could not locate executable fort
            customize IntelItaniumFCompiler
            Could not locate executable efort
            Could not locate executable efc
            customize IntelEM64TFCompiler
            customize GnuFCompiler
            Could not locate executable g77
            customize G95FCompiler
            Could not locate executable g95
            customize PathScaleFCompiler
            Could not locate executable pathf95
            customize NAGFORCompiler
            Could not locate executable nagfor
            don't know how to compile Fortran code on platform 'posix'
            C compiler: /srv/conda/envs/notebook/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /srv/conda/envs/notebook/include -fPIC -O2 -isystem /srv/conda/envs/notebook/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /srv/conda/envs/notebook/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /srv/conda/envs/notebook/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/srv/conda/envs/notebook/include/python3.9 -c'
            x86_64-conda-linux-gnu-cc: _configtest.c
            /srv/conda/envs/notebook/bin/x86_64-conda-linux-gnu-cc _configtest.o -o _configtest
            /srv/conda/envs/notebook/bin/../lib/gcc/x86_64-conda-linux-gnu/12.1.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lgcc
            /srv/conda/envs/notebook/bin/../lib/gcc/x86_64-conda-linux-gnu/12.1.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lgcc
            collect2: error: ld returned 1 exit status
            failure.
            removing: _configtest.c _configtest.o _configtest.o.d
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/setup.py", line 443, in <module>
                setup_package()
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/setup.py", line 435, in setup_package
                setup(**metadata)
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/numpy/distutils/core.py", line 171, in setup
                return old_setup(**new_attr)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
                return distutils.core.setup(**attrs)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
                return run_commands(dist)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                dist.run_commands()
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
                self.run_command(cmd)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
                super().run_command(command)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                cmd_obj.run()
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/numpy/distutils/command/install.py", line 62, in run
                r = self.setuptools_run()
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/numpy/distutils/command/install.py", line 36, in setuptools_run
                return distutils_install.run(self)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 698, in run
                self.run_command('build')
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
                self.distribution.run_command(command)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
                super().run_command(command)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                cmd_obj.run()
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/numpy/distutils/command/build.py", line 47, in run
                old_build.run(self)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
                self.run_command(cmd_name)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
                self.distribution.run_command(command)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
                super().run_command(command)
              File "/srv/conda/envs/notebook/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                cmd_obj.run()
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/numpy/distutils/command/build_src.py", line 142, in run
                self.build_sources()
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/numpy/distutils/command/build_src.py", line 153, in build_sources
                self.build_library_sources(*libname_info)
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/numpy/distutils/command/build_src.py", line 286, in build_library_sources
                sources = self.generate_sources(sources, (lib_name, build_info))
              File "/tmp/pip-install-db5bfz0b/numpy_461db2cffacb4d36bfe6ada6a07d4bb1/numpy/distutils/command/build_src.py", line 369, in generate_sources
                source = func(extension, build_dir)
              File "numpy/core/setup.py", line 669, in get_mathlib_info
                raise RuntimeError("Broken toolchain: cannot link a simple C program")
            RuntimeError: Broken toolchain: cannot link a simple C program
            [end of output]
```

**Comment by TomAugspurger** [comment]
Looks like that library has a dependency on some version that's incompatible with the NumPy installed in the environment from https://github.com/microsoft/planetary-computer-containers (https://github.com/microsoft/planetary-computer-containers/blob/dabe6bb565aa24b9cae590751429790b2e251a65/python/conda-linux-64.lock#L351 specifically).

I'm not sure why, but pip is deciding to build NumPy from source rather than using a wheel for that platform. That's not going to work since there isn't a C compiler in that environment.

**Comment by ghidalgo3** [comment]
The hub is no longer available.
